# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4oEf-7wJ8AC4cZzbIVBXwlitFjacVom
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import re
from collections import Counter

# Veriyi okuyoruz.
df = pd.read_csv('/content/drive/MyDrive/AI_Human.csv')

word_freq = Counter()

print("Lowercase, Punctuations ve Tokenization İşlemleri gerçekleştiriliyor.")

for text in df['text']:
    if pd.isna(text): continue
    # Küçük harf ve noktalama temizliği (Sadece sayım için geçici işlem)
    clean_text = str(text).lower()
    clean_text = re.sub(r'[^a-z\s]', '', clean_text)
    # Kelimeleri sayaca ekle
    word_freq.update(clean_text.split())

# Sonuçları göster
print("\n" + "="*40)
print(f"{'Kelime':<15} | {'Frekans':<10}")
print("="*40)
for word, freq in word_freq.most_common(30):
    print(f"{word:<15} | {freq:<10}")

import nltk
from nltk.corpus import stopwords

# Gerekli paketi indiriyoruz ve listeyi hazırlıyoruz.
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 1. 'not' kelimesi AI için olumsuzluk belirtmekte kullanılan bir ifadedir. AI genel olarak insan gibi kısaltmalar yapmak yerine is not demeyi tercih eder.
# Bu noktada insan AI ayrımında modelin daha iyi kavramasına yardımcı olabilir.
if 'not' in stop_words:
    stop_words.remove('not')

# 2.'no' kelimesi de benzer bir göreve sahip olduğundan onu da NLTK stop_word listesinden çıkarıyoruz ve metinde kalmasını sağlıyoruz.
if 'no' in stop_words:
    stop_words.remove('no')

# Analiz sonucunda eklemeye karar verdiğimiz kelimeler "people ve students" oluyor. Çünkü bizim için metin AI mı insan mı tarafından yazıldı önemlidir.
# Bu kelimeler ise metin konusu hakkında bilgi verdiğinden silinmesi sorun teşkil etmemektedir.
# "would" kelimesi de sık tekrar eden bir kelimedir ama AI genelde daha resmi metinler üretebildiğinden AI tarafından kullanılabilir bir kelimedir.
# Yani metin AI mı, İnsan mı tarafından yazıldı bunu anlamamızda yardımcı olabilir, bu sebeple silinmemesine karar verildi.

stop_words.update(['students', 'people'])

def final_preprocess(text):
    if pd.isna(text): return None
    # 1. Adım Lowercase & 2. Adım Punctuations Removal
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    # 3. Adım Tokenization & 4. Adım Stop_word Removal
    tokens = [w for w in text.split() if w not in stop_words]
    return " ".join(tokens)

print("Stop_word İşlemi gerçekleştiriliyor!")

df['clean_text'] = df['text'].apply(final_preprocess)

# Boş kalan satırları temizliyoruz.
df = df.dropna(subset=['clean_text'])

print(f"İşlem Tamamlandı! Veri seti ön işleme adımlarından geçirilerek sonraki adımlara hazır hale gedli. Kalan satır sayısı: {len(df)}")

print("\n" + "="*60)
print("ÖN İŞLEME SONUCU (BÜYÜK VERİ SETİ)")
print("="*60)
print(f"ORİJİNAL: {df['text'].iloc[0][:150]}...")
print("-" * 60)
print(f"TEMİZLENMİŞ: {df['clean_text'].iloc[0][:150]}...")
print("="*60)

# Feature Extraction kısmını farklı bir dosyada yapıcağımız için bu şekilde kaydediyoruz.
df[['clean_text', 'generated']].to_csv('/content/drive/MyDrive/cleaned_data.csv', index=False)
print("Temizlenmiş veri kaydedildi!")

# Veri setini Github!a yüklemek için küçük bir örneklem alıyoruz.
import pandas as pd

# 1. Veri setini yükle
df = pd.read_csv('/content/drive/MyDrive/AI_Human.csv')

# 2. Her sınıftan (AI ve İnsan) eşit sayıda (250'şer) örnek al
# 'generated' sütununa göre grupla ve her gruptan rastgele seç
sample_df = df.groupby('generated', group_keys=False).apply(lambda x: x.sample(n=250, random_state=42))

# 3. İndeksleri karıştır (Verilerin alt alta aynı sınıftan gelmemesi için)
sample_df = sample_df.sample(frac=1, random_state=42).reset_index(drop=True)

# 4. GitHub'a yüklemek üzere kaydet
sample_df.to_csv('/content/drive/MyDrive/dataset_sample.csv', index=False)

# Kontrol için sınıfların dağılımını yazdıralım
print("Sınıf Dağılımı:\n", sample_df['generated'].value_counts())