# -*- coding: utf-8 -*-
"""evaluate_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cns0QyZ49WBO9s12IgXmGwab_Xa09QhQ
"""

from google.colab import drive
drive.mount('/content/drive')

"""------------- 1. Logistic Regreyon Modeli Değerlendirme Aşaması -------------"""

import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve, average_precision_score

# Önce gerekli olanları yüklüyoruz.
model = joblib.load('/content/drive/MyDrive/logistic_model_trained.joblib')
X_test = joblib.load('/content/drive/MyDrive/X_test.joblib')
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')

# 1. Confusion Matrix Fonksiyonunu oluşturuyoruz.
def plot_model_results(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='RdPu', cbar=False,
                xticklabels=['Human (0)', 'AI (1)'],
                yticklabels=['Human (0)', 'AI (1)'])

    plt.title(f'{model_name} - Confusion Matrix', fontsize=14)
    plt.xlabel('Tahmin Edilen Sınıf', fontsize=12)
    plt.ylabel('Gerçek Sınıf', fontsize=12)
    plt.tight_layout() # Grafiği çerçeveye oturturuoruz.
    plt.show()

# 2. Precision-Recall ve Metrik Analizi Fonksiyonunu oluşturuyoruz.
def plot_precision_recall_analysis(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    y_probs = model.predict_proba(X_test)[:, 1]

    report = classification_report(y_test, y_pred, output_dict=True)
    f1_macro = report["macro avg"]["f1-score"]

    precision, recall, _ = precision_recall_curve(y_test, y_probs)
    avg_precision = average_precision_score(y_test, y_probs)

    plt.figure(figsize=(9, 6))
    plt.plot(recall, precision, color='teal', lw=3, label=f'{model_name} (AP = {avg_precision:.4f})')
    plt.fill_between(recall, precision, alpha=0.1, color='teal')

    plt.xlabel('Recall (Duyarlılık)', fontsize=12)
    plt.ylabel('Precision (Kesinlik)', fontsize=12)
    plt.title(f'Precision-Recall Trade-off ({model_name})', fontsize=14)
    plt.legend(loc="lower left")
    plt.grid(True, linestyle='--', alpha=0.5)

    plt.text(0.1, 0.2, f'Genel F1-Score: {f1_macro:.4f}',
             bbox=dict(facecolor='white', alpha=0.8, edgecolor='teal'),
             fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.show()

# 3. Sınıf Bazlı Karşılaştırma Fonksiyonu  oluşturuyoruz.
def plot_class_comparison(model, X_test, y_test):
    y_pred = model.predict(X_test)
    report_dict = classification_report(y_test, y_pred, output_dict=True)

    metrics = ['precision', 'recall', 'f1-score']
    human_scores = [report_dict['0'][m] for m in metrics]
    ai_scores = [report_dict['1'][m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    plt.figure(figsize=(10, 6))
    plt.bar(x - width/2, human_scores, width, label='Human (Sınıf 0)', color='#3498db')
    plt.bar(x + width/2, ai_scores, width, label='AI (Sınıf 1)', color='#e74c3c')

    plt.ylabel('Skorlar')
    plt.title('Sınıf Bazlı Performans Karşılaştırması')
    plt.xticks(x, ['Precision', 'Recall', 'F1-Score'])
    plt.ylim(0.95, 1.01)
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

# 4. Performans Tablosu Fonksiyonunu oluşturuyoruz.
def display_metrics_table(model, X_test, y_test):
    y_pred = model.predict(X_test)
    # Raporu sözlük formatında alıyoruz.
    report = classification_report(y_test, y_pred, output_dict=True)

    # DataFrame oluşturup sadece ana sınıfları ( Precision, Recall, F1 sütunları ve 0, 1 satırları)
    # alıyoruz.
    report_df = pd.DataFrame(report).transpose()
    final_table = report_df.iloc[:2, :3]

    # Görsel düzenleme yapıyoruz.
    final_table.index = ['İnsan (Human - 0)', 'Yapay Zeka (AI - 1)']
    final_table.columns = ['Hassasiyet (Precision)', 'Duyarlılık (Recall)', 'F1-Skoru']

    print("\n" + "-------- MODEL PERFORMANS TABLOSU --------")
    display(final_table)


# --- ÇALIŞTIRMA AŞAMASI---

print("--- Detaylı Analiz ---")

# 1. Grafik_Confusion Matrix'i gösteriyoruz.
plot_model_results(model, X_test, y_test, "Logistic Regression")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 2. Grafik_Precision Recall İlişkisini Grafik Formatında gösteriyoruz.
plot_precision_recall_analysis(model, X_test, y_test, "Logistic Regression")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 3. Grafik_Sınıf Bazlı Sütun Grafiğini gösteriyoruz.
plot_class_comparison(model, X_test, y_test)
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 4. Tablo Formatında Sonuçları gösteriyoruz.
display_metrics_table(model, X_test, y_test)

"""------------- 2. Naive Bayes Modeli Değerlendirme Aşaması -------------"""

import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve, average_precision_score

# Önce gerekli olanları yüklüyoruz.
model = joblib.load('/content/drive/MyDrive/nb_model_trained.joblib')
X_test = joblib.load('/content/drive/MyDrive/X_test.joblib')
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')

# 1. Confusion Matrix Fonksiyonunu oluşturuyoruz.
def plot_model_results(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='RdPu', cbar=False,
                xticklabels=['Human (0)', 'AI (1)'],
                yticklabels=['Human (0)', 'AI (1)'])

    plt.title(f'{model_name} - Confusion Matrix', fontsize=14)
    plt.xlabel('Tahmin Edilen Sınıf', fontsize=12)
    plt.ylabel('Gerçek Sınıf', fontsize=12)
    plt.tight_layout() # Grafiği çerçeveye oturturuoruz.
    plt.show()

# 2. Precision-Recall ve Metrik Analizi Fonksiyonunu oluşturuyoruz.
def plot_precision_recall_analysis(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    y_probs = model.predict_proba(X_test)[:, 1]

    report = classification_report(y_test, y_pred, output_dict=True)
    f1_macro = report["macro avg"]["f1-score"]

    precision, recall, _ = precision_recall_curve(y_test, y_probs)
    avg_precision = average_precision_score(y_test, y_probs)

    plt.figure(figsize=(9, 6))
    plt.plot(recall, precision, color='teal', lw=3, label=f'{model_name} (AP = {avg_precision:.4f})')
    plt.fill_between(recall, precision, alpha=0.1, color='teal')

    plt.xlabel('Recall (Duyarlılık)', fontsize=12)
    plt.ylabel('Precision (Kesinlik)', fontsize=12)
    plt.title(f'Precision-Recall Trade-off ({model_name})', fontsize=14)
    plt.legend(loc="lower left")
    plt.grid(True, linestyle='--', alpha=0.5)

    plt.text(0.1, 0.2, f'Genel F1-Score: {f1_macro:.4f}',
             bbox=dict(facecolor='white', alpha=0.8, edgecolor='teal'),
             fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.show()

# 3. Sınıf Bazlı Karşılaştırma Fonksiyonu  oluşturuyoruz.
def plot_class_comparison(model, X_test, y_test):
    y_pred = model.predict(X_test)
    report_dict = classification_report(y_test, y_pred, output_dict=True)

    metrics = ['precision', 'recall', 'f1-score']
    human_scores = [report_dict['0'][m] for m in metrics]
    ai_scores = [report_dict['1'][m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    plt.figure(figsize=(10, 6))
    plt.bar(x - width/2, human_scores, width, label='Human (Sınıf 0)', color='#3498db')
    plt.bar(x + width/2, ai_scores, width, label='AI (Sınıf 1)', color='#e74c3c')

    plt.ylabel('Skorlar')
    plt.title('Sınıf Bazlı Performans Karşılaştırması')
    plt.xticks(x, ['Precision', 'Recall', 'F1-Score'])
    plt.ylim(0.95, 1.01)
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

# 4. Performans Tablosu Fonksiyonunu oluşturuyoruz.
def display_metrics_table(model, X_test, y_test):
    y_pred = model.predict(X_test)
    # Raporu sözlük formatında alıyoruz.
    report = classification_report(y_test, y_pred, output_dict=True)

    # DataFrame oluşturup sadece ana sınıfları ( Precision, Recall, F1 sütunları ve 0, 1 satırları)
    # alıyoruz.
    report_df = pd.DataFrame(report).transpose()
    final_table = report_df.iloc[:2, :3]

    # Görsel düzenleme yapıyoruz.
    final_table.index = ['İnsan (Human - 0)', 'Yapay Zeka (AI - 1)']
    final_table.columns = ['Hassasiyet (Precision)', 'Duyarlılık (Recall)', 'F1-Skoru']

    print("\n" + "-------- MODEL PERFORMANS TABLOSU --------")
    display(final_table)


# --- ÇALIŞTIRMA AŞAMASI---

print("--- Detaylı Analiz ---")

# 1. Grafik_Confusion Matrix'i gösteriyoruz.
plot_model_results(model, X_test, y_test, "Naive Bayes")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 2. Grafik_Precision Recall İlişkisini Grafik Formatında gösteriyoruz.
plot_precision_recall_analysis(model, X_test, y_test, "Naive Bayes")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 3. Grafik_Sınıf Bazlı Sütun Grafiğini gösteriyoruz.
plot_class_comparison(model, X_test, y_test)
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 4. Tablo Formatında Sonuçları gösteriyoruz.
display_metrics_table(model, X_test, y_test)

"""------------- 3. LinearSVC ( SVM Alt Modeli ) Modeli Değerlendirme Aşaması -------------"""

import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve, average_precision_score

# Önce gerekli olanları yüklüyoruz.
model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')
X_test = joblib.load('/content/drive/MyDrive/X_test.joblib')
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')

# 1. Confusion Matrix Fonksiyonunu oluşturuyoruz.
def plot_model_results(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='RdPu', cbar=False,
                xticklabels=['Human (0)', 'AI (1)'],
                yticklabels=['Human (0)', 'AI (1)'])

    plt.title(f'{model_name} - Confusion Matrix', fontsize=14)
    plt.xlabel('Tahmin Edilen Sınıf', fontsize=12)
    plt.ylabel('Gerçek Sınıf', fontsize=12)
    plt.tight_layout() # Grafiği çerçeveye oturturuoruz.
    plt.show()

# 2. Precision-Recall ve Metrik Analizi Fonksiyonunu oluşturuyoruz.
def plot_precision_recall_analysis(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    y_probs = model.decision_function(X_test)

    report = classification_report(y_test, y_pred, output_dict=True)
    f1_macro = report["macro avg"]["f1-score"]

    precision, recall, _ = precision_recall_curve(y_test, y_probs)
    avg_precision = average_precision_score(y_test, y_probs)

    plt.figure(figsize=(9, 6))
    plt.plot(recall, precision, color='teal', lw=3, label=f'{model_name} (AP = {avg_precision:.4f})')
    plt.fill_between(recall, precision, alpha=0.1, color='teal')

    plt.xlabel('Recall (Duyarlılık)', fontsize=12)
    plt.ylabel('Precision (Kesinlik)', fontsize=12)
    plt.title(f'Precision-Recall Trade-off ({model_name})', fontsize=14)
    plt.legend(loc="lower left")
    plt.grid(True, linestyle='--', alpha=0.5)

    plt.text(0.1, 0.2, f'Genel F1-Score: {f1_macro:.4f}',
             bbox=dict(facecolor='white', alpha=0.8, edgecolor='teal'),
             fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.show()

# 3. Sınıf Bazlı Karşılaştırma Fonksiyonu  oluşturuyoruz.
def plot_class_comparison(model, X_test, y_test):
    y_pred = model.predict(X_test)
    report_dict = classification_report(y_test, y_pred, output_dict=True)

    metrics = ['precision', 'recall', 'f1-score']
    human_scores = [report_dict['0'][m] for m in metrics]
    ai_scores = [report_dict['1'][m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    plt.figure(figsize=(10, 6))
    plt.bar(x - width/2, human_scores, width, label='Human (Sınıf 0)', color='#3498db')
    plt.bar(x + width/2, ai_scores, width, label='AI (Sınıf 1)', color='#e74c3c')

    plt.ylabel('Skorlar')
    plt.title('Sınıf Bazlı Performans Karşılaştırması')
    plt.xticks(x, ['Precision', 'Recall', 'F1-Score'])
    plt.ylim(0.95, 1.01)
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

# 4. Performans Tablosu Fonksiyonunu oluşturuyoruz.
def display_metrics_table(model, X_test, y_test):
    y_pred = model.predict(X_test)
    # Raporu sözlük formatında alıyoruz.
    report = classification_report(y_test, y_pred, output_dict=True)

    # DataFrame oluşturup sadece ana sınıfları ( Precision, Recall, F1 sütunları ve 0, 1 satırları)
    # alıyoruz.
    report_df = pd.DataFrame(report).transpose()
    final_table = report_df.iloc[:2, :3]

    # Görsel düzenleme yapıyoruz.
    final_table.index = ['İnsan (Human - 0)', 'Yapay Zeka (AI - 1)']
    final_table.columns = ['Hassasiyet (Precision)', 'Duyarlılık (Recall)', 'F1-Skoru']

    print("\n" + "-------- MODEL PERFORMANS TABLOSU --------")
    display(final_table)


# --- ÇALIŞTIRMA AŞAMASI---

print("--- Detaylı Analiz ---")

# 1. Grafik_Confusion Matrix'i gösteriyoruz.
plot_model_results(model, X_test, y_test, "LinearSVC")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 2. Grafik_Precision Recall İlişkisini Grafik Formatında gösteriyoruz.
plot_precision_recall_analysis(model, X_test, y_test, "LinearSVC")
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 3. Grafik_Sınıf Bazlı Sütun Grafiğini gösteriyoruz.
plot_class_comparison(model, X_test, y_test)
# Grafikler arasına hem boşluk hem çizgi ekliyoruz böylece daha iyi bir görünüm elde ediyoruz.
print("\n" + "="*100 + "\n")

# 4. Tablo Formatında Sonuçları gösteriyoruz.
display_metrics_table(model, X_test, y_test)