# -*- coding: utf-8 -*-
"""feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bptQE-DMIMLOasLadaSzFyO6UME2lRnO
"""

from google.colab import drive
drive.mount('/content/drive')

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# 1. Temizlenmiş veriyi yüklüyoruz.
print("Temizlenmiş veri yükleniyor...")
df = pd.read_csv('/content/drive/MyDrive/cleaned_data.csv')

# CSV'de boş satırlar olabilir o yüzden NaN kontrolü yapıyoruz.
df = df.dropna(subset=['clean_text'])

print("Feature Extraction İşlemi için TF-IDF Metodu ile gerçekleştiriliyor!")

# 1. TF-IDF Nesnesini Yapılandırıyoruz
# max_features: Belleği korumak ve en önemli kelimelere odaklanmak için veri setindeki
# en çok ayırt edici 20.000 kelimesini seçerek sözlüğe alıyoruz.
# ngram_range: (1, 2) yaparak hem tekli kelimeleri hem de ikili kelime gruplarını
# (örn: "is not") yakalıyoruz. Bu modelin AI ve insanın kelimeleri nasıl birleştirdiğini
# öğrenmesi konusunda önemlidir.
tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1, 2))

# 2. Vektörleştirme İşlemini Uyguluyoruz
# Bu işlem metinleri devasa bir sayı matrisine (Sparse Matrix) dönüştürür.
# Fit işlemi ile öğrenme sağlanıyor ve burda 20 000 kelimelik sözlük oluşturuyoruz. Ve bu sözlük
# ile matematiksel olarak yaptığımız gibi TF-IDF (nadir) hesbı yapıyoruz ve her metinde bu sözlükteki
# kelimelerin olması durumunda skorlar belirleniyor, olmaması durumunda 0 olarak belirlenir ve
# seyrek matris oluşturuyoruz. Arada sıfır değerlerinin olması sebebiyle böyle denir.
X = tfidf.fit_transform(df['clean_text'])

# 3. Hedef Değişkenimizin (AI mı İnsan mı) ne olduğunu alıyoruz. Bu ileride hata hesabında işimize
# yarayacaktır.
# RAM tasarrufu sağlamak için y değerlerini en küçük tam sayı tipine çeviriyoruz.
y = df['generated'].astype('int8').values

print(f"Vektörleştirme tamamlandı!")
print(f"X matris boyutu: {X.shape}")
# Stop_word temizlemesi sonrası satır sayısı, en çok ayırt edici olan belirlediğimiz kelime sayısı

# TF-IDF modelini bir dosyaya kaydet (Joblib kullanarak denedik.)
import joblib
joblib.dump(tfidf, '/content/drive/MyDrive/tfidf_model.joblib')

print("TF-IDF modeli başarıyla kaydedildi!")
# Sayısal matrisi ve etiketleri kaydediyoruz
joblib.dump(X, '/content/drive/MyDrive/X_matrix.joblib')
joblib.dump(y, '/content/drive/MyDrive/y_labels.joblib')
print("Vektörler ve etiketler kaydedildi!")