# -*- coding: utf-8 -*-
"""optional_advanced_component.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sT3Iaiy-EC0H1OC-8VJUqnqeS9Xposqf
"""

from google.colab import drive
drive.mount('/content/drive')

"""-------------- 1. Feature Importance Analysis (Özellik Önemi Analizi) --------------"""

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Kaydettiğin dosya yollarını buraya yaz.
tfidf = joblib.load('/content/drive/MyDrive/tfidf_model.joblib')
model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')

print("Vektörleştirici ve Model başarıyla yüklendi!")

def plot_svc_feature_importance(tfidf_vectorizer, model, n_top=20):
    # 1. Kelime isimlerini (features) al
    feature_names = tfidf_vectorizer.get_feature_names_out()

    # 2. LinearSVC katsayılarını al (LinearSVC'de model.coef_[0] içindedir)
    coefficients = model.coef_[0]

    # 3. Bir DataFrame oluşturup sırala
    feature_importance = pd.DataFrame({'feature': feature_names, 'coef': coefficients})

    # AI tarafı için en yüksek katsayılar (Pozitif)
    top_ai = feature_importance.sort_values(by='coef', ascending=False).head(n_top)

    # İnsan tarafı için en düşük katsayılar (Negatif)
    top_human = feature_importance.sort_values(by='coef', ascending=True).head(n_top)

    # 4. Görselleştirme
    plt.figure(figsize=(15, 8))

    # AI Grafiği
    plt.subplot(1, 2, 1)
    plt.barh(top_ai['feature'], top_ai['coef'], color='salmon')
    plt.xlabel("Katsayı (Pozitif -> AI)")
    plt.title(f"AI Metni İçin En Belirleyici {n_top} Kelime")
    plt.gca().invert_yaxis() # En önemliler en üstte görünsün

    # İnsan Grafiği
    plt.subplot(1, 2, 2)
    plt.barh(top_human['feature'], top_human['coef'], color='skyblue')
    plt.xlabel("Katsayı (Negatif -> İnsan)")
    plt.title(f"İnsan Metni İçin En Belirleyici {n_top} Kelime")
    plt.gca().invert_yaxis()

    plt.tight_layout()
    plt.show()

# Fonksiyonu çalıştır
plot_svc_feature_importance(tfidf, model)

"""-------------- 1. Error Analysis (Hata Analizi) --------------"""

# Ham veri seti gibi düşünüp error analysis de "text" demiştik ama cleaned_text de sütun ismi
# "clean_text" olarak karşımıza çıktı.
df = pd.read_csv('/content/drive/MyDrive/cleaned_data.csv')
print("Dosyadaki Sütun İsimleri:", df.columns.tolist())

import joblib
import pandas as pd

# 1. HAZIRLANMIŞ VERİLERİ YÜKLE
# Daha önce kaydettiğimiz temizlenmiş pandas dosyasını ve vektörleri çekiyoruz
X_test_pandas = pd.read_csv('/content/drive/MyDrive/X_test_pandas_cleaned.csv')
X_test_vec = joblib.load('/content/drive/MyDrive/X_test.joblib')
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')

# 2. MODELİ YÜKLE
model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')

# 3. TAHMİNLER VE GÜVEN SKORLARI
y_pred = model.predict(X_test_vec)
scores = model.decision_function(X_test_vec)

# 4. HATALARI TESPİT ET VE BİLGİLERİ EKLE
error_mask = (y_pred != y_test)
errors_df = X_test_pandas[error_mask].copy()
errors_df['modelin_tahmini'] = y_pred[error_mask]
errors_df['guven_skoru'] = scores[error_mask]

# 5. ETİKETLERİ İSİMLENDİR
label_map = {0: "İnsan", 1: "AI"}
errors_df['gercek_etiket_adi'] = errors_df['generated'].map(label_map)
errors_df['tahmin_edilen_ad'] = errors_df['modelin_tahmini'].map(label_map)

# 6. İSTATİSTİKLERİ HESAPLA
fp = len(errors_df[errors_df['generated'] == 0]) # İnsan -> AI
fn = len(errors_df[errors_df['generated'] == 1]) # AI -> İnsan

# 7. ANALİZ VE YAZDIRMA
print(f"{'='*30}\nLINEAR SVC HATA ANALİZİ (HIZLI MOD)\n{'='*30}")
print(f"Toplam Test Örneği: {len(y_test)}")
print(f"Tespit Edilen Toplam Hata Sayısı: {len(errors_df)}")
print(f"Yanlış Pozitif (İnsan->AI): {fp}")
print(f"Yanlış Negatif (AI->İnsan): {fn}")

pd.set_option('display.max_colwidth', 500)
print("\n--- LINEAR SVM EN ÇOK YANILDIĞI 10 METİN ---")
print(errors_df[['clean_text', 'gercek_etiket_adi', 'tahmin_edilen_ad', 'guven_skoru']].head(10))

"""Error Analysis Aşamasında modelin yanlış tahmin etmiş olduğu 97 test metni içinden ilk 10 metin sıralanmıştır. Bu ilk 10 metnin incelemesi sonucunda, modelin emin olmayarak düşük güven skoruyla bu yanlış tahminleri gerçekleştirdiği gözlemlenmiştir.
Bunun dışında yazım yanlışlarının yer aldığı AI tarafından oluşturulmuş metinlerin ve çok düzenli ve akademik bir dilin kullanıldığı insan tarafından oluşturulmuş metinlerin veri setinde yer aldığı görülmüştür. Bu durumun modelin kafasını karıştırdığı ve hata yapmasına yol açtığı farkedilmiştir. Bu da bize modelin aslında "İnsan" ve "AI" ayrımını kavradığını göstermiştir. Modein AI metninin stilini (kurallı ve dil bilgisine uygun, daha akademik metinler) ve İnsan metninin stilini (daha çok günlük ifadeler, belirsizlik içeren kelimeler ve yazım hataları gibi) iyi bir şekilde öğrendiğini kanıtlamıştır.

-------------- 2. Error Analysis - Logistic Regresyon - Naive Bayes (Hata Analizi) --------------
"""

import joblib
import pandas as pd
import numpy as np

# 1. ÖNCEDEN HAZIRLADIĞIN VERİLERİ YÜKLE
# split ve dropna işlemlerini tekrar yapmamak için kaydettiğin temiz pandas dosyasını kullanıyoruz
X_test_pandas = pd.read_csv('/content/drive/MyDrive/X_test_pandas_cleaned.csv')
X_test_vec = joblib.load('/content/drive/MyDrive/X_test.joblib')
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')

# 2. KALAN MODELLERİ YÜKLE
models_to_analyze = {
    "Logistic Regression": '/content/drive/MyDrive/logistic_model_trained.joblib',
    "Naive Bayes": '/content/drive/MyDrive/nb_model_trained.joblib'
}

label_map = {0: "İnsan", 1: "AI"}
pd.set_option('display.max_colwidth', 500)

for name, path in models_to_analyze.items():
    print(f"\n{'-'*30}\n{name.upper()} ANALİZİ BAŞLIYOR\n{'-'*30}")

    # Modeli yüklüyoruz.
    current_model = joblib.load(path)

    # Tahminleri alıyoruz.
    y_pred = current_model.predict(X_test_vec)

    # GÜVEN SKORU HESAPLAMA
    # Logistic Regression için decision_function, Naive Bayes için predict_proba kullandık.
    if hasattr(current_model, "decision_function"):
        scores = current_model.decision_function(X_test_vec)
    else:
        # Naive Bayes için, AI olma olasılığının 0.5'ten uzaklığına bakıyoruz.
        probs = current_model.predict_proba(X_test_vec)[:, 1]
        scores = probs - 0.5

    # Hataları tespit ediyoruz.
    error_mask = (y_pred != y_test)
    errors_df = X_test_pandas[error_mask].copy()
    errors_df['modelin_tahmini'] = y_pred[error_mask]
    errors_df['guven_skoru'] = scores[error_mask]

    # İsimlendirmeleri yapıyoruz.
    errors_df['gercek_etiket_adi'] = errors_df['generated'].map(label_map)
    errors_df['tahmin_edilen_ad'] = errors_df['modelin_tahmini'].map(label_map)

    # İstatistikleri yazdırıyoruz.
    print(f"Toplam Test Örneği: {len(y_test)}")
    print(f"Tespit Edilen Hata Sayısı: {len(errors_df)}")

    fp = len(errors_df[errors_df['generated'] == 0])
    fn = len(errors_df[errors_df['generated'] == 1])
    print(f"Yanlış Pozitif (İnsan->AI): {fp}")
    print(f"Yanlış Negatif (AI->İnsan): {fn}")

    # İlk 10 hatayı gösteriyoruz.
    print(f"\n--- {name} EN ÇOK YANILDIĞI 10 METİN ---")
    print(errors_df[['clean_text', 'gercek_etiket_adi', 'tahmin_edilen_ad', 'guven_skoru']].head(10))

print("\nAnaliz tamamlandı!")

"""-------------- 3. Error Analysis ( Karşılaştırmalı Hata Analizi) --------------"""

import joblib
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

# 1. Hazır verileri yüklüyoruz.
X_test_pandas = pd.read_csv('/content/drive/MyDrive/X_test_pandas_cleaned.csv')
X_test_vec = joblib.load('/content/drive/MyDrive/X_test.joblib') # Vektörler
y_test = joblib.load('/content/drive/MyDrive/y_test.joblib')     # Gerçek etiketler

# 2. Modelleri yüklüyoruz.
svm_model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')
lr_model = joblib.load('/content/drive/MyDrive/logistic_model_trained.joblib')
nb_model = joblib.load('/content/drive/MyDrive/nb_model_trained.joblib')


def get_error_stats(model, name):
    preds = model.predict(X_test_vec)
    errors = X_test_pandas[preds != y_test].copy()

    # Hata türlerini ayırıyoruz. (False Positive / False Negative)
    # 0: İnsan, 1: AI
    fp = errors[(errors['generated'] == 0) & (preds[preds != y_test] == 1)] # İnsana AI demiş
    fn = errors[(errors['generated'] == 1) & (preds[preds != y_test] == 0)] # AI'ya İnsan demiş

    print(f"\n=== {name} HATA ANALİZİ ===")
    print(f"Toplam Hata: {len(errors)}")
    print(f"İnsan olduğu halde AI denilen (False Positive): {len(fp)}")
    print(f"AI olduğu halde İnsan denilen (False Negative): {len(fn)}")
    return errors

# 3. Karşılaştırmalı sonuçları alıyoruz.
svm_errors = get_error_stats(svm_model, "Linear SVM")
lr_errors = get_error_stats(lr_model, "Logistic Regression")
nb_errors = get_error_stats(nb_model, "Naive Bayes")

# 4. Ortak hataları buluyoruz. (Üç modelin de hata yaptığı metinler)
# Önce SVM ve LR'nin ortak hatalarını bulup, sonra NB ile kesişimine bakıyoruz.
common_indices = svm_errors.index.intersection(lr_errors.index).intersection(nb_errors.index)
common_errors = X_test_pandas.loc[common_indices]

print(f"\n--- KARŞILAŞTIRMALI ÖZET ---")
print(f"Her üç modelin de ortak olarak yanıldığı metin sayısı: {len(common_errors)}")

# 5. TÜM HATALARI AYRI AYRI VE ORTAK OLARAK KAYDET
svm_errors.to_csv('/content/drive/MyDrive/svm_butun_hatalar.csv', index=False)
lr_errors.to_csv('/content/drive/MyDrive/lr_butun_hatalar.csv', index=False)
nb_errors.to_csv('/content/drive/MyDrive/nb_butun_hatalar.csv', index=False)
common_errors.to_csv('/content/drive/MyDrive/tum_modeller_ortak_hatalar.csv', index=False)

print("\nHata dosyaları Drive'a başarıyla kaydedildi!")

# Ortak hatalardan ilk 5 örneği ekrana yazdırıyoruz.
print("\n--- HER ÜÇ MODELİN DE ORTAK YANILDIĞI ÖRNEK METİNLER ---")
pd.set_option('display.max_colwidth', 500) # Metinlerin tam görünmesini sağlıyoruz.

# Eğer ortak hata varsa gösteriyoruz.
if len(common_errors) > 0:
    # Gerçek etiketini de yanına ekleyerek gösteriyoruz.
    # (Hepsinde tahmin yanlış olduğu için gerçek etiket neyse tam tersini tahmin etmişlerdir)
    print(common_errors[['clean_text', 'generated']].head(5))
else:
    print("Her üç modelin aynı anda yanıldığı bir metin bulunamadı.")

"""-------------- 4. Explainable AI Methods (LIME) --------------"""

!pip install lime

import joblib
import pandas as pd
import numpy as np
from lime.lime_text import LimeTextExplainer
from sklearn.pipeline import make_pipeline
from IPython.display import display, HTML

# 1. GEREKLİ DOSYALARI YÜKLE
model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')
vectorizer = joblib.load('/content/drive/MyDrive/tfidf_model.joblib')
common_errors = pd.read_csv('/content/drive/MyDrive/tum_modeller_ortak_hatalar.csv')

# 2. LIME İÇİN PİPELINE VE YARDIMCI FONKSİYON
c = make_pipeline(vectorizer, model)

# LinearSVM tek sütunlu karar üretir ama binary classificationda LIME iki sütunlu karar bekler.
# Burda bu dönüşüm yapılır.
def svm_predict_proba(texts):
    decision_scores = c.decision_function(texts)
    # LIME'ın beklediği [P(negatif), P(pozitif)] yapısı
    return np.vstack([-decision_scores, decision_scores]).T

# 3. LIME KURULUMU
class_names = ['İnsan', 'AI']
explainer = LimeTextExplainer(class_names=class_names)

# 4. İLK İKİ HATAYI DÖNGÜ İLE İNCELEME İŞLEMİ YAPILIYOR.
for idx in range(2):
    sample_text = str(common_errors.iloc[idx]['clean_text'])
    true_label = int(common_errors.iloc[idx]['generated'])

    print(f"\n{'='*50}")
    print(f"ÖRNEK ANALİZİ #{idx+1}")
    print(f"GERÇEK ETİKET: {class_names[true_label]}")
    print(f"{'='*50}")

    # LIME Açıklaması
    exp = explainer.explain_instance(
        sample_text,
        svm_predict_proba,
        num_features=10,
        labels=(1,)
    )

    # Görselleştirmeyi notebook içinde göster
    exp.show_in_notebook(text=True)
