# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-m1AGODMU5LK-lEZl-3NA_ZpTrOPboG2
"""

from google.colab import drive
drive.mount('/content/drive')

"""----------------- 1. Logic Regression Model -----------------"""

import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Kaydettiğimiz sayısal verileri yüklüyoruz.
print("Vektörler ve etiketler yükleniyor!")
X = joblib.load('/content/drive/MyDrive/X_matrix.joblib')
y = joblib.load('/content/drive/MyDrive/y_labels.joblib')

# 2. Veriyi Eğitim ve Test setlerine ayırıyoruz
# test_size=0.2 belirledik: Verinin %80'i ile öğrenme gerçekleşecek, %20'si ile sınav yapılacak.
# stratify=y kullandık: AI/İnsan dağılımının her iki sette de eşit olmasını istedik.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. Modelin Kurulması ve Eğitilmesi
# solver='saga': 487 bin satır gibi büyük verilerde en hızlı ve kararlı çalışan algoritmadır. Bu sebeple tercih ettik.
# n_jobs=-1: Bilgisayarındaki tüm işlemci çekirdeklerini kullanarak eğitimi hızlandırmak için tercih ettik.
lr_model = LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1)

print("Logistic Regression eğitimi gerçekleştiriliyor!")
lr_model.fit(X_train, y_train)

# 4. Tahmin Yapılıyor.
print("Tahminler yapılıyor!")
y_pred = lr_model.predict(X_test)

# 5. Sonuçların Analizi gerçekleştiriliyor.
print("\n--- Logistic Regression Performans Sonuçları ---")
print(f"Genel Doğruluk (Accuracy): {accuracy_score(y_test, y_pred):.4f}")

# 6. Eğitilmiş Modeli ve Test Verilerini İleride Yapacağımız Evaluation Aşaması için Kaydediyoruz.
joblib.dump(lr_model, '/content/drive/MyDrive/logistic_model_trained.joblib')
joblib.dump(X_test, '/content/drive/MyDrive/X_test.joblib')
joblib.dump(y_test, '/content/drive/MyDrive/y_test.joblib')
print("\nModel ve test verileri başarıyla kaydedildi!")

"""----------------- Logic Regresyon Modelinin Test Aşaması -----------------"""

import joblib
import re
import nltk
from nltk.corpus import stopwords

# 1. Gerekli altyapıyı hazırlıyoruz.
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Özel ayarlarımızı koruyoruz: 'not' ve 'no' stop_word listesinden çıkarılıyor, 'students' ve 'people' ise ekleniyor.
if 'not' in stop_words: stop_words.remove('not')
if 'no' in stop_words: stop_words.remove('no')
stop_words.update(['students', 'people'])

# 2. Vektör ve model yükleniyor.
print("Vektör ve model yükleniyor!")
tfidf = joblib.load('/content/drive/MyDrive/tfidf_model.joblib')
model = joblib.load('/content/drive/MyDrive/logistic_model_trained.joblib')

# 3. Data Preprocessing Aşamasında tanımladığımız'final_preprocess' fonksiyonunu kullanıyoruz.
def final_preprocess_for_test(text):
    if not text: return ""
    # Lowercase & Punctuations Removal
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    # Tokenization & Stop_word Removal
    tokens = [w for w in text.split() if w not in stop_words]
    return " ".join(tokens)

# 4. Tahmin Fonksiyonu tanımlıyoruz.
def predict_new_text(raw_text):
    cleaned = final_preprocess_for_test(raw_text)
    vectorized = tfidf.transform([cleaned])

    prediction = model.predict(vectorized)[0]
    prob = model.predict_proba(vectorized)[0]

    label = "Yapay Zeka (AI)" if prediction == 1 else "İnsan (Human)"
    confidence = prob[prediction] * 100

    print("\n" + "="*50)
    print(f"Giriş: {raw_text[:100]}...")
    print(f"Temizlenmiş: {cleaned[:100]}...")
    print(f"SONUÇ: {label} (%{confidence:.2f} Güven)")
    print("="*50)

# --- ŞİMDİ TEST ET ---
my_text = "I am an engineering student. I do not think that this project is easy, but I am learning a lot about machine learning."
ai_text = "Artificial intelligence offers various benefits in modern education. It is not intended to replace teachers but to assist them."

predict_new_text(my_text)
predict_new_text(ai_text)

"""----------------- 2. Multinomial Naive Bayes Model -----------------"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import joblib

# 1. Modeli oluşturuyoruz.
# Naive Bayes'te genelde alpha=0.1 veya 1 (Laplace smoothing) kullanılır. Bunun sebebi "Zero Probability" problemidir.
# Naive Bayes olasılıkların çarpımına dayanan bir modeldir. Bu sebeple bir insana ait bir metinde belirli bir kelime hiç geçmiyorsa hesaplama sonucu direk "0" olur.
# Ve modelin diğer kelimeleri göz ardı etmesine ve hatalı bir tahmin yapmasına sebep olur.
# Alpha değeri 0.1 veya 1 olarak seçilebilir. Küçük bir değer belirliyoruz, böylece direk 0 demek yerine 0.1 diyoruz.
# Bu da veri setinin genel yapısını bozmamış, modelin tahmin yeteneğini büyük oranda etkilememiş oluyor.
# 1. Kaydettiğimiz sayısal verileri yüklüyoruz.

print("Vektörler ve etiketler yükleniyor!")
X = joblib.load('/content/drive/MyDrive/X_matrix.joblib')
y = joblib.load('/content/drive/MyDrive/y_labels.joblib')

nb_model = MultinomialNB(alpha=0.1)

print("Naive Bayes modeli eğitimi gerçekleştiriliyor!")
nb_model.fit(X_train, y_train)

# 2. Tahmin Yap
y_pred_nb = nb_model.predict(X_test)

# 3. Sonuçları Görüntüle
print("\n--- Naive Bayes Performans Sonuçları ---")
print(f"Genel Doğruluk (Accuracy): {accuracy_score(y_test, y_pred_nb):.4f}")

# 4. Modeli Kaydet
print("Naive Bayes Modeli başarıyla kaydedildi!")
joblib.dump(nb_model, '/content/drive/MyDrive/nb_model_trained.joblib')

"""----------------- 2. Multinomial Naive Bayes Modelin Test Aşaması -----------------"""

import joblib
import re
import nltk
from nltk.corpus import stopwords

# 1. Gerekli altyapıyı hazırlıyoruz.
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Özel ayarlarımızı koruyoruz: 'not' ve 'no' stop_word listesinden çıkarılıyor, 'students' ve 'people' ise ekleniyor.
if 'not' in stop_words: stop_words.remove('not')
if 'no' in stop_words: stop_words.remove('no')
stop_words.update(['students', 'people'])

# 2. Vektör ve model yükleniyor.
print("Vektör ve model yükleniyor!")
tfidf = joblib.load('/content/drive/MyDrive/tfidf_model.joblib')
model = joblib.load('/content/drive/MyDrive/nb_model_trained.joblib')

# 3. Data Preprocessing Aşamasında tanımladığımız 'final_preprocess' fonksiyonunu kullanıyoruz.
def final_preprocess_for_test(text):
    if not text: return ""
    # Lowercase & Punctuations Removal
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    # Tokenization & Stop_word Removal
    tokens = [w for w in text.split() if w not in stop_words]
    return " ".join(tokens)

# 4. Tahmin Fonksiyonu tanımlıyoruz.
def predict_new_text(raw_text):
    cleaned = final_preprocess_for_test(raw_text)
    vectorized = tfidf.transform([cleaned])

    prediction = model.predict(vectorized)[0]
    prob = model.predict_proba(vectorized)[0]

    label = "Yapay Zeka (AI)" if prediction == 1 else "İnsan (Human)"
    confidence = prob[prediction] * 100

    print("\n" + "="*50)
    print(f"Giriş: {raw_text[:100]}...")
    print(f"Temizlenmiş: {cleaned[:100]}...")
    print(f"SONUÇ: {label} (%{confidence:.2f} Güven)")
    print("="*50)

# --- ŞİMDİ TEST ET ---
my_text = "I am an engineering student. I do not think that this project is easy, but I am learning a lot about machine learning."
ai_text = "Artificial intelligence offers various benefits in modern education. It is not intended to replace teachers but to assist them."

predict_new_text(my_text)
predict_new_text(ai_text)

"""----------------- 2. Linear SVC (Linear Support Vector Machine) Model -----------------"""

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

# 1. Kaydettiğimiz sayısal verileri yüklüyoruz.
print("Vektörler ve etiketler yükleniyor!")
X = joblib.load('/content/drive/MyDrive/X_matrix.joblib')
y = joblib.load('/content/drive/MyDrive/y_labels.joblib')

# Modelin Tanımlamasını yapıyoruz.
# LinearSVC, büyük veri setlerinde standart SVC'den kat kat hızlıdır ve daha yüksek doğruluk verir.
# Bu sebeple bir SVC türü olan LinearSVM tercih edilmiştir.
svm_model = LinearSVC(random_state=42, max_iter=2000)

print("LinearSVC eğitimi gerçekleştiriliyor!")
svm_model.fit(X_train, y_train)

# 2. Tahmin ve Hızlı Kontrol
y_pred_svm = svm_model.predict(X_test)

# 3. Sonuçları Görüntüle
print("\n--- LinearSVC Performans Sonuçları ---")
print(f"Genel Doğruluk (Accuracy): {accuracy_score(y_test, y_pred_svm):.4f}")

# 4. Modeli Kaydetme
print("LinearSVC modeli başarıyla kaydedidi!")
joblib.dump(svm_model, '/content/drive/MyDrive/linearsvm_model_trained.joblib')

"""----------------- 2. LinearSVC Modeli Test Aşaması -----------------"""

import joblib
import re
import nltk
from nltk.corpus import stopwords

# 1. Gerekli altyapıyı hazırlıyoruz.
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Özel ayarlarımızı koruyoruz: 'not' ve 'no' stop_word listesinden çıkarılıyor, 'students' ve 'people' ise ekleniyor.
if 'not' in stop_words: stop_words.remove('not')
if 'no' in stop_words: stop_words.remove('no')
stop_words.update(['students', 'people'])

# 2. Vektör ve model yükleniyor.
print("Vektör ve model yükleniyor!")
tfidf = joblib.load('/content/drive/MyDrive/tfidf_model.joblib')
model = joblib.load('/content/drive/MyDrive/linearsvm_model_trained.joblib')

# 3. Data Preprocessing Aşamasında tanımladığımız'final_preprocess' fonksiyonunu kullanıyoruz.
def final_preprocess_for_test(text):
    if not text: return ""
    # Lowercase & Punctuations Removal
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    # Tokenization & Stop_word Removal
    tokens = [w for w in text.split() if w not in stop_words]
    return " ".join(tokens)

# 4. Tahmin Fonksiyonu tanımlıyoruz.
def predict_new_text(raw_text):
    cleaned = final_preprocess_for_test(raw_text)
    vectorized = tfidf.transform([cleaned])

    prediction = model.predict(vectorized)[0]
    # LinearSVC'de predict_proba yerine decision_function kullanılır.
    # Bu değer sınırdan (0) ne kadar uzak olduğunu söyler. Çünkü LinearSVC verileri uzayda göstererek onları doğrusal bir düzlem ile ayıran bir modeldir.
    score = model.decision_function(vectorized)[0]

    label = "Yapay Zeka (AI)" if prediction == 1 else "İnsan (Human)"

    # Skor 0'dan büyükse AI, küçükse İnsan'dır.
    print("\n" + "="*50)
    print(f"Giriş: {raw_text[:100]}...")
    print(f"Temizlenmiş: {cleaned[:100]}...")
    print(f"SONUÇ: {label} (Güven Skoru: {score:.4f})")
    print("="*50)

# --- ŞİMDİ TEST ET ---
my_text = "I am an engineering student. I do not think that this project is easy, but I am learning a lot about machine learning."
ai_text = "Artificial intelligence offers various benefits in modern education. It is not intended to replace teachers but to assist them."

predict_new_text(my_text)
predict_new_text(ai_text)